package com.zhangsan.boot.dao;

import com.zhangsan.boot.entity.TfSettleNotifyEvent;

public interface TfSettleNotifyEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_settle_notify_event
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_settle_notify_event
     *
     * @mbg.generated
     */
    int insert(TfSettleNotifyEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_settle_notify_event
     *
     * @mbg.generated
     */
    int insertSelective(TfSettleNotifyEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_settle_notify_event
     *
     * @mbg.generated
     */
    TfSettleNotifyEvent selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_settle_notify_event
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TfSettleNotifyEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_settle_notify_event
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TfSettleNotifyEvent record);
}