package com.zhangsan.boot.entity;

import java.util.Date;

public class TfSettleNotifyEvent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf_settle_notify_event.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf_settle_notify_event.business_id
     *
     * @mbg.generated
     */
    private String businessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf_settle_notify_event.msg
     *
     * @mbg.generated
     */
    private String msg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf_settle_notify_event.consume_status
     *
     * @mbg.generated
     */
    private Integer consumeStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf_settle_notify_event.err_code
     *
     * @mbg.generated
     */
    private String errCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf_settle_notify_event.creation_time
     *
     * @mbg.generated
     */
    private Date creationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf_settle_notify_event.creator
     *
     * @mbg.generated
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf_settle_notify_event.modified_time
     *
     * @mbg.generated
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf_settle_notify_event.modifier
     *
     * @mbg.generated
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf_settle_notify_event.is_deleted
     *
     * @mbg.generated
     */
    private Byte isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf_settle_notify_event.id
     *
     * @return the value of tf_settle_notify_event.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf_settle_notify_event.id
     *
     * @param id the value for tf_settle_notify_event.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf_settle_notify_event.business_id
     *
     * @return the value of tf_settle_notify_event.business_id
     *
     * @mbg.generated
     */
    public String getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf_settle_notify_event.business_id
     *
     * @param businessId the value for tf_settle_notify_event.business_id
     *
     * @mbg.generated
     */
    public void setBusinessId(String businessId) {
        this.businessId = businessId == null ? null : businessId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf_settle_notify_event.msg
     *
     * @return the value of tf_settle_notify_event.msg
     *
     * @mbg.generated
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf_settle_notify_event.msg
     *
     * @param msg the value for tf_settle_notify_event.msg
     *
     * @mbg.generated
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf_settle_notify_event.consume_status
     *
     * @return the value of tf_settle_notify_event.consume_status
     *
     * @mbg.generated
     */
    public Integer getConsumeStatus() {
        return consumeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf_settle_notify_event.consume_status
     *
     * @param consumeStatus the value for tf_settle_notify_event.consume_status
     *
     * @mbg.generated
     */
    public void setConsumeStatus(Integer consumeStatus) {
        this.consumeStatus = consumeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf_settle_notify_event.err_code
     *
     * @return the value of tf_settle_notify_event.err_code
     *
     * @mbg.generated
     */
    public String getErrCode() {
        return errCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf_settle_notify_event.err_code
     *
     * @param errCode the value for tf_settle_notify_event.err_code
     *
     * @mbg.generated
     */
    public void setErrCode(String errCode) {
        this.errCode = errCode == null ? null : errCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf_settle_notify_event.creation_time
     *
     * @return the value of tf_settle_notify_event.creation_time
     *
     * @mbg.generated
     */
    public Date getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf_settle_notify_event.creation_time
     *
     * @param creationTime the value for tf_settle_notify_event.creation_time
     *
     * @mbg.generated
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf_settle_notify_event.creator
     *
     * @return the value of tf_settle_notify_event.creator
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf_settle_notify_event.creator
     *
     * @param creator the value for tf_settle_notify_event.creator
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf_settle_notify_event.modified_time
     *
     * @return the value of tf_settle_notify_event.modified_time
     *
     * @mbg.generated
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf_settle_notify_event.modified_time
     *
     * @param modifiedTime the value for tf_settle_notify_event.modified_time
     *
     * @mbg.generated
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf_settle_notify_event.modifier
     *
     * @return the value of tf_settle_notify_event.modifier
     *
     * @mbg.generated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf_settle_notify_event.modifier
     *
     * @param modifier the value for tf_settle_notify_event.modifier
     *
     * @mbg.generated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf_settle_notify_event.is_deleted
     *
     * @return the value of tf_settle_notify_event.is_deleted
     *
     * @mbg.generated
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf_settle_notify_event.is_deleted
     *
     * @param isDeleted the value for tf_settle_notify_event.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }
}